Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "/mnt/c/Users/freezzze/sf_practice/6", "/home/vagrant"
  config.vm.provision "shell", path: "provision.sh"
end