version: "3.3"

services:

  php:
    build:
      context: ./
      args:
        buildno: 22042001
    container_name: php
    hostname: php-container
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
    healthcheck:
      test: curl -s http://nginx | grep works
      interval: 30s
      timeout: 2s
      retries: 10

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx-container
    restart: unless-stopped
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - 80:80
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
